### PR TITLE
add license to package.json

### PR DESCRIPTION
**Pull request by wooorm**
/cc @jonathanong Sorry to ping, but I’d also :+1: a 1.0.0 version (~~insert left-pad joke here~~)

### CODE REVIEW

**Comment by Trott** [comment]
4 years later...landed in https://github.com/Trott/trim/commit/cd1c1caaefd0655828f1d456912a3f866eb42464.

**Comment by Trott** [comment]
> I’d also 👍 a 1.0.0 version

Agreed...and done!

**Comment by Trott** [comment]
https://www.npmjs.com/package/trim:

image

@wooorm Can you close this PR? I'm able to publish to npm but I can't do anything with this repository unfortunately.

**Comment by wooorm** [comment]
Yeah! Thanks for taking care of this, @Trott!

Btw, as you own the npm package now, would it make sense to update the [`repository` in `package.json`](https://github.com/Trott/trim/blob/b0e7e19075f96b74b2e35a3e5e74bd68c4e4942a/package.json#L17) to point to your repo? Currently, npm is pointing here, but I think it would be better to start directing issues to your repo.

And maybe an issue here that says `Trott/trim` is a maintained version?

**Comment by Trott** [comment]
> Btw, as you own the npm package now, would it make sense to update the [`repository` in `package.json`](https://github.com/Trott/trim/blob/b0e7e19075f96b74b2e35a3e5e74bd68c4e4942a/package.json#L17) to point to your repo? Currently, npm is pointing here, but I think it would be better to start directing issues to your repo.

If updates keep being necessary (hopefully not?) and I don't get access to this repo, I'll probably do that at some point. I'd prefer to leave it here and (if necessary) maintain it here.

Do you know if there's any reason not to generally discourage people from using this in favor of String.prototype.trim()? A deprecation would seem to be in order but maybe there's some `component.json` magic I don't know about or something like that.

**Comment by wooorm** [comment]
I don’t think component is used anymore, although I’m sure it’s running in some places. Most engines support `trim` now, but till about 2 years ago I was including this package (from npm) to ensure my code worked everywhere.

I think deprecating `trim@1.0.0` is good! Component worked based on GH repos, so I don’t see how deprecating the npm package hurts it.

**Pull request closed without merging**
